import type { Metadata } from "next";
import Starfield from "react-starfield";
import "./globals.css";


export const metadata: Metadata = {
  title: "Ziad Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className=" relative overflow-hidden">{children}</main>
        <Starfield
        starCount={1000}
        starColor={[255, 255, 255]}
        speedFactor={0.05}
        backgroundColor="black"
        />
      </body>
    </html>
  );
}
